-- PetOne AI Supabase schema for the current cloud MVP.
-- Run this file in Supabase Dashboard > SQL Editor before launching the app.
--
-- Production note:
-- These tables intentionally do not enable RLS yet because the current app has
-- no login/shop ownership flow. Before distributing to real customers, add
-- auth, shop_id/tenant ownership, and Row Level Security policies.

create table if not exists public.product_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  sku text not null unique,
  barcode text,
  category_id bigint references public.product_categories(id) on delete set null,
  brand text,
  cost_price numeric not null default 0,
  selling_price numeric not null default 0,
  stock_quantity integer not null default 0,
  low_stock_threshold integer not null default 5,
  unit text default 'cái',
  description text,
  track_batch boolean not null default false,
  allow_direct_sale boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  total_amount numeric not null,
  created_at timestamptz not null default now()
);

create table if not exists public.sale_items (
  id bigint generated by default as identity primary key,
  sale_id bigint not null references public.sales(id) on delete cascade,
  product_id bigint not null references public.products(id),
  quantity integer not null,
  unit_price numeric not null
);

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  description text not null,
  amount numeric not null,
  created_at timestamptz not null default now()
);

create index if not exists products_category_id_idx on public.products(category_id);
create index if not exists products_created_at_idx on public.products(created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row
execute function public.set_updated_at();

insert into public.product_categories (name)
values
  ('Thức ăn'),
  ('Phụ kiện'),
  ('Thuốc & Vitamin'),
  ('Đồ chơi'),
  ('Vệ sinh'),
  ('Dịch vụ')
on conflict (name) do nothing;
